### ISSUE TITLE
restore system error

### ISSUE THREAD

**Issue by timesleader** [mauronofrio/android_device_oneplus_fajita#1]
recovery.log

tar_extract_file(): failed to extract //system/system/framework/boot-core-oj.vdex !!!
I:Unable to extract tar archive '/data/media/0/TWRP/BACKUPS/a0ce7cf8/2018-01-01--00-35-47/system.ext4.win001'

**Comment by mauronofrio** [comment]
Someone report me it, maybe is needed something more, i will investigate on it, can you make some test? Can you check if it gives error only with system?

**Comment by timesleader** [comment]
you can release your twrp  download  here，i will test it

**Comment by mauronofrio** [comment]
Can you share your recovery.log?

**Comment by timesleader** [comment]
https://drive.google.com/file/d/1XhBd1Wl_lS1uFqxlr5DKs-b4pWv0vHyJ/view?usp=sharing

**Comment by timesleader** [comment]
it does not sove the problem

**Comment by mauronofrio** [comment]
Can you always share your log?

**Comment by timesleader** [comment]
the same log。。。

**Comment by mauronofrio** [comment]
I want to read before for the others commits and for you error try to check this:

https://forum.xda-developers.com/oneplus-6/how-to/255-error-twrp-backup-restore-999-t3801632

**Comment by mauronofrio** [comment]
Can you tell me if when you make the backup you have "system_image" option?

**Comment by timesleader** [comment]
yes we can backup system_image，and resore system_image sucessfully  。。。

**Comment by mauronofrio** [comment]
So next time use that option instead of system, "system" is backuped like files, "system_image" is backup like an img so it's better

**Comment by timesleader** [comment]
Ok, for the time being, it can only be solved like this.

**Comment by mauronofrio** [comment]
Not a problem, thanks to make this issue, maybe can be usefull for some other one

**Comment by timesleader** [comment]
Happy cooperation ， thx！
